#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop ge360-analitica.service >/dev/null 2>&1 || true
        systemctl disable ge360-analitica.service >/dev/null 2>&1 || true
    fi
fi
